- name: Create DBA user
  oracle_user:
          hostname={{ inventory_hostname }}
          service_name={{ oracle_db.pdb }}
          user={{ user }}
          password={{ oracle_db.passwd }}
          schema={{ item.0.schema }}
          schema_password_hash={{ item.0.schema_password_hash }}
          state={{ item.0.state }}
          default_temp_tablespace={{ item.0.default_temp_tablespace }}
          default_tablespace={{ item.0.default_tablespace }}
          grants={{ item.1 }}
          update_password=on_create
  environment: oracle_env
  with_subelements:
     - dba_user
     - grants
  tags: users


- name: Create Application Users
  oracle_user:
          hostname={{ inventory_hostname }}
          service_name={{ oracle_db.pdb }}
          user={{ user }}
          password={{ oracle_db.passwd }}
          schema={{ item.0.schema }}
          schema_password={{ item.0.schema_password | default (omit) }}
          state={{ item.0.state }}
          default_temp_tablespace={{ item.0.default_temp_tablespace }}
          default_tablespace={{ item.0.default_tablespace }}
          grants={{ item.1 }}
          update_password=on_create
  environment: oracle_env
  with_subelements:
     - application_user
     - grants
  tags: users
