---
- name: sweoug1
  group: "[sweoug]"
  box: oravirt/ol73
  ram: 4096
  cpu: 1
  ip: 192.168.9.231
  os_extra_disk: "yes"
  os_extra_disk_size: 50
  os_num_extra_disk: 1
  db_extra_disk: "yes"
  db_extra_disk_size: 10
  db_num_extra_disk: 1
  #private_key: /home/miksan/.vagrant.d/insecure_private_key
  private_key: /Users/miksan/.vagrant.d/insecure_private_key

