---
# tasks file for host
- name: Install packages
  yum: name={{ item }} state=installed
  with_items: "{{os_packages}}"
  tags: os_packages, oscheck

- name: Disable firewall
  service: name=firewalld state=stopped enabled=no

# - name: Disable selinux (permanently)
#   selinux: state=disabled
#
# - name: Disable selinux (runtime)
#   shell: setenforce 0
#   ignore_errors: true

# - name: Check dns for host
#   command: nslookup {{ ansible_hostname }}
#   register: ns
#   ignore_errors: True
#   tags: etchosts

- name: Add host to /etc/hosts
  lineinfile: dest=/etc/hosts regexp='.*{{ ansible_fqdn }}$' line="{{ ansible_default_ipv4.address }} {{ ansible_hostname }} {{ ansible_fqdn }}" state=present
  # when: "'find {{ ansible_hostname }}: NXDOMAIN' in ns.stdout or 'find {{ ansible_hostname }}: SERVFAIL' in ns.stdout "
  tags: etchosts

- name: Add group(s)
  group: name={{ item }} state=present
  with_items:
      - "{{oracle_groups}}"
  tags: group

- name: Add Oracle user
  user: name={{ oracle_user.name }}  group={{ oracle_user.primgroup }} groups={{ oracle_user.othergroups }} generate_ssh_key=yes append=yes state=present password={{ oracle_user.passwd }}
  #user: name=oracle  group=oinstall groups=dba generate_ssh_key=yes append=yes state=present password="$6$0xHoAXXF$K75HKb64Hcb/CEcr3YEj2LGERi/U2moJgsCK.ztGxLsKoaXc4UBiNZPL0hlxB5ng6GL.gyipfQOOXplzcdgvD0"
  tags: user

- name: Kernel settings
  sysctl: name={{ item.name }} value="{{ item.value }}" state=present reload=yes
  with_items: "{{oracle_sysctl}}"
  tags: sysctl

- name: PAM config
  lineinfile: dest=/etc/pam.d/login state=present line="session required pam_limits.so"
  tags: pamconfig

- name: Security limits
  template: src=templates/oracle-seclimits.conf.j2 dest=/etc/security/limits.d/99-oracle-limits.conf backup=yes
  tags: seclimit
